services:
  api:
    build:
      context: ../api
      dockerfile: ../.docker/api/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ../api:/api
      - /api/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    networks:
      - cedh-tools
    restart: unless-stopped

networks:
  cedh-tools:

